import OnvoBase from "../base.js";
import { Automation } from "../types/index.js";
export declare class OnvoAutomations extends OnvoBase {
    list(): Promise<{
        created_at: string;
        created_by: string;
        dashboard: string;
        description: string | null;
        email_format: string;
        email_subject: string;
        enabled: boolean;
        id: string;
        last_run_at: string | null;
        last_updated_at: string;
        last_updated_by: string | null;
        next_run_at: string | null;
        output_format: string;
        recipient_type: string;
        recipients: string[] | null;
        schedule: string;
        team: string;
        timezone: string;
        title: string;
    }[]>;
    get(id: string): Promise<{
        created_at: string;
        created_by: string;
        dashboard: string;
        description: string | null;
        email_format: string;
        email_subject: string;
        enabled: boolean;
        id: string;
        last_run_at: string | null;
        last_updated_at: string;
        last_updated_by: string | null;
        next_run_at: string | null;
        output_format: string;
        recipient_type: string;
        recipients: string[] | null;
        schedule: string;
        team: string;
        timezone: string;
        title: string;
    }>;
    delete(id: string): Promise<{
        success: true;
    }>;
    update(id: string, body: Partial<Automation>): Promise<{
        created_at: string;
        created_by: string;
        dashboard: string;
        description: string | null;
        email_format: string;
        email_subject: string;
        enabled: boolean;
        id: string;
        last_run_at: string | null;
        last_updated_at: string;
        last_updated_by: string | null;
        next_run_at: string | null;
        output_format: string;
        recipient_type: string;
        recipients: string[] | null;
        schedule: string;
        team: string;
        timezone: string;
        title: string;
    }>;
    create(body: Partial<Automation>): Promise<{
        created_at: string;
        created_by: string;
        dashboard: string;
        description: string | null;
        email_format: string;
        email_subject: string;
        enabled: boolean;
        id: string;
        last_run_at: string | null;
        last_updated_at: string;
        last_updated_by: string | null;
        next_run_at: string | null;
        output_format: string;
        recipient_type: string;
        recipients: string[] | null;
        schedule: string;
        team: string;
        timezone: string;
        title: string;
    }>;
}
